### ISSUE TITLE
Why add $$$$ after each English sentence?

### ISSUE THREAD

**Issue by caozhen-alex** [HLTCHKUST/Mem2Seq#12]
Hi,
Why add `$$$$` after each English sentence?
https://github.com/HLTCHKUST/Mem2Seq/blob/84a2ccdb3255680ee19c3b94985517e8718ced65/utils/utils_NMT.py#L138

**Comment by andreamad8** [comment]
$$$$ this token is the Sentinel used to decide whether to copy or not a certain token.
