### ISSUE TITLE
Code fails on evaluation for kvr 

### ISSUE THREAD

**Issue by isaacmg** [HLTCHKUST/Mem2Seq#13]
I'm running the following command
`python3 main_train.py -lr=0.001 -layer=1 -hdd=128 -dr=0.2 -dec=Mem2Seq -bsz=8 -ds=kvr -t=` I'm in the process of upgrading to torch 0.4.0 and I already changed the line to `top_ptr_i.squeeze()[i].item()`. It only fails on the 97 of the 99 evaluation for the code which makes me think that it is only some weird data. 
Here is the error code:
`02-27 00:04 STARTING EVALUATION
R:0.0855,W:72.8617:  99% 97/98 [00:22<00:00,  4.58it/s]Traceback (most recent call last):
  File "main_train.py", line 62, in <module>
    acc = model.evaluate(dev,avg_best, BLEU)    
  File "/content/Mem2Seq/models/Mem2Seq.py", line 281, in evaluate
    data_dev[2],data_dev[3],data_dev[4],data_dev[5],data_dev[6]) 
  File "/content/Mem2Seq/models/Mem2Seq.py", line 202, in evaluate_batch
    next_in = [top_ptr_i.squeeze()[i].item() if(int(toppi.squeeze()[i].item()) < input_lengths[i]-1) else topvi.squeeze()[i].item() for i in range(batch_size)]
  File "/content/Mem2Seq/models/Mem2Seq.py", line 202, in <listcomp>
    next_in = [top_ptr_i.squeeze()[i].item() if(int(toppi.squeeze()[i].item()) < input_lengths[i]-1) else topvi.squeeze()[i].item() for i in range(batch_size)]
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number`
BTW my branch is located here https://github.com/isaacmg/Mem2Seq

Thanks for the help.

**Comment by andreamad8** [comment]
Which version of pytorch are you running? 

Because the code has been developed using version 3, the newer version may raise errors

Andrea

**Comment by isaacmg** [comment]
1.0.1 but I already converted things to .item()

**Comment by andreamad8** [comment]
ok, we never had this error with the older version. 

Seams like squeeze() remove a dimension and then it cannot access the element cause is not a tensor. I have to check the code if you find a way to make it run in V.1 we could also merge to master. 

Andrea

**Comment by isaacmg** [comment]
I did some debugging and for all the other examples in the evaluation the tensor seems to have a size of `torch.Size[1,8]` before the squeeze operation. Whereas for the last one that fails it's `torch.Size([1, 1])` . Any idea why this would be?

**Comment by andreamad8** [comment]
Seams like the batch size dimension have been wiped out, maybe in a previous part of the code.

Maybe print the dimension in output from each iteration, and check if any tensor has been squeezed. 

Let me know. 

Andrea

**Comment by isaacmg** [comment]
Yes I think it is a problem with batch size. Normally I get something like this 
``` size below
8
torch.Size([1, 8])
```
But on the 97th I get
``` size below
7
torch.Size([1, 1])
```

**Comment by jasonwu0731** [comment]
Hi @isaacmg 

You got the error because the squeeze() function will return torch.Size([1, 1]) tensor into a scalar.
Please check the updated code.

https://github.com/HLTCHKUST/Mem2Seq/blob/master/models/Mem2Seq.py
