### ISSUE TITLE
Can I run this code on pytorch 0.4 now?

### ISSUE THREAD

**Issue by MBCmbc** [HLTCHKUST/Mem2Seq#14]
Can I run this code on pytorch 0.4 now?

**Comment by andreamad8** [comment]
No, we still support just pytorch 0.3. 

@isaacmg is trying to make it run in pytorch 1.0, maybe follow the other issue.

Best 

Andrea

**Comment by jasonwu0731** [comment]
Yes you can check the latest Mem2Seq.py
It's fine to run in PyTorch 1.0
