### ISSUE TITLE
when i run PTRUNK, i got an error

### ISSUE THREAD

**Issue by Abbyyan** [HLTCHKUST/Mem2Seq#16]
hello, when i try to run 
'python3 main_train.py -lr=0.001 -layer=1 -hdd=128 -dr=0.2 -dec=PTRUNK -bsz=8 -ds=babi -t=1'
, there happens a TypeError in models/enc_PTRUNK.py, line 347
cannot assign 'torch.autograd.variable.Variable'  as parameter 'v'(torch.nn.Parameter or None expected),by the way ,i use pytorch 0.3. Can you help me please?

**Comment by andreamad8** [comment]
Hi, 

comment line 347: 
```
# self.v = self.v.cuda() 
```
and add ```.cuda()``` in line 337: 
```
self.v.data.normal_(mean=0, std=stdv).cuda()
```

**Comment by Abbyyan** [comment]
Thank you very much . It helps me a lot!

**Comment by andreamad8** [comment]
No problems

**Comment by haoningz** [comment]
Hello,

I met the same problem. In pytorch 0.3.1, After commenting and adding .cuda() and running, it shows:
'Traceback (most recent call last):
  File "main_train.py", line 59, in <module>
    len(data[1]),10.0,0.5,i==0)
  File "/export/scratch/zhanghaoning/Mem2Seq-master/models/enc_PTRUNK.py", line 134, in train_batch
    top_ptr_i = torch.gather(input_batches,0,toppi.view(1, -1))
RuntimeError: gather(): argument 'index' (position 2) must be Variable, not torch.cuda.LongTensor'.
Could you please help solve it? Thanks.
