### ISSUE TITLE
predict word is out of vocabulary

### ISSUE THREAD

**Issue by shaomai00** [HLTCHKUST/Mem2Seq#2]
Thank you for your great work first!
When I run:
python3 main_train.py -lr=0.001 -layer=1 -hdd=12 -dr=0.0 -dec=Mem2Seq -bsz=2 -ds=babi -t=1
I got this problem:
Traceback (most recent call last):
  File "Mem2Seq/main_train.py", line 70, in <module>
    acc = model.evaluate(dev,avg_best, BLEU)    
  File "Mem2Seq\models\Mem2Seq.py", line 272, in evaluate
    data_dev[2],data_dev[3],data_dev[4],data_dev[5],data_dev[6], data_dev[-4], data_dev[-3])          
  File "Mem2Seq\models\Mem2Seq.py", line 223, in evaluate_batch
    temp.append(self.lang.index2word[ind])
KeyError: tensor(21, device='cuda:0')

I guess OOV may be the reason and I made a test.I printed the 'ind' and the index2word dic, I found the 'ind' is 93 while the max key in index2word is 92:rome.
I'm wondering why could this happen when the word 'UNK' is in the dictionary and how should I handle it? Should I just ignore it and set it to 'UNK' or something else?

Thank you again~

**Comment by shaomai00** [comment]
yeah...it's true. it works fine that add .item() after topvi.squeeze()[i].
Thank you again.

**Comment by andreamad8** [comment]
Great, 

pls be also careful to add .item() everywhere. In particular in toppi, else it will compare tensor to an integer, and it will always return false (i.e. always getting from vocab).

So use something like: 
int(toppi.squeeze()[i].item()) 

Best
Andrea
