### ISSUE TITLE
Data loading reverse KB entry

### ISSUE THREAD

**Issue by nurav** [HLTCHKUST/Mem2Seq#21]
Hi, I was wondering why you were inverting the KB entry to predict. It would be great if I can have an explanation for your reasoning behind it.

**Comment by andreamad8** [comment]
This is actually just an implementation detail. We reverse it because we need to copy the entity in the last position, but for a matter of simplicity, we want it in the first position. Hence we reverse the KB entry.

I hope this answers your question
