### ISSUE TITLE
ERROR When running 

### ISSUE THREAD

**Issue by SunZhiyuanS** [HLTCHKUST/Mem2Seq#22]
When I was running the following code: python3 main_train.py -lr=0.001 -layer=1 -hdd=128 -dr=0.2 -dec=Mem2Seq -bsz=8 -ds=babi -t=1，an error show up and I don't know how to solve it,plz help me!

05-24 23:49 Dialog Accuracy:	0.088
Traceback (most recent call last):
  File "F:/Code/Mem2Seq/Mem2Seq/main_train.py", line 62, in <module>
    acc = model.evaluate(dev,avg_best, BLEU)    
  File "F:\Code\Mem2Seq\Mem2Seq\models\Mem2Seq.py", line 361, in evaluate
    bleu_score = moses_multi_bleu(np.array(hyp), np.array(ref), lowercase=True) 
  File "F:\Code\Mem2Seq\Mem2Seq\utils\measures.py", line 97, in moses_multi_bleu
    with open(hypothesis_file.name, "r") as read_pred:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Stan\\AppData\\Local\\Temp\\tmpg1tkn92y'

**Comment by andreamad8** [comment]
the bleu scorer generates temp folders. So you need to provide the read/write access to the folder. 

Or you can delete it.

I will close the issue since this problem is related to the BLUE scorer and not directly our code. 

I hope this helps. 

Andrea

**Comment by SunZhiyuanS** [comment]
@andreamad8 Thanks!But how can I provide the read/write access to the folder?

**Comment by andreamad8** [comment]
Hi 

maybe this will help

https://superuser.com/questions/126073/chmod-to-allow-read-and-write-permissions-for-directory

**Comment by SunZhiyuanS** [comment]
@andreamad8 I have run main_train.py succeed and now I want to test it.What does the  path_name_model mean in this code In this code "-path=path_name_model",I tried “./save/mem2seq-BABI” but it didn't work.

**Comment by andreamad8** [comment]
Is the path to the folder that the model saves.

**Comment by SunZhiyuanS** [comment]
@andreamad8  I'm very greatful , thanks for you patiently explain !

**Comment by andreamad8** [comment]
No problems, let me know if you have any other question in the code. 

Ps: This is how -path should look like:

-path= /save/mem2seq-BABI/name_of_the_file_saved

Andrea

**Comment by 1551389181** [comment]
I want to ask, if I successfully train the model, can I make inputs, and it will give me the output?

**Comment by 1551389181** [comment]
I want to ask, if I successfully train the model, can I make inputs, and it will give me the predicted output? If so, what should I do.
