### ISSUE TITLE
Pre-processing questions

### ISSUE THREAD

**Issue by isaacmg** [HLTCHKUST/Mem2Seq#23]
Hello, I was just hoping you could clarify some of the preprocessing code as I'm trying to convert MultiWOZ to the same format to use with the model. First of all I'm assuming that `read_entities.py` is what is producing the train.txt, test.txt etc for the KVR dataset. So the goal of preprocessing seems to be to get them all into the format `0 2_miles road_block_nearby parking_garage poi dish_parking`. So I assume the 0 means that they are a KB entry correct? Then the 1, 2,3 are for the actual dialogue turns.  Also for the KB entries how do you decide how many items to have? Some seem to be the standard KB triplet `ravenswood_shopping_center distance 6_miles` whereas other seem to be longer like `4_miles heavy_traffic coffee_or_tea_place poi philz`? What is the criteria for determining that? Also are there are any other preprocessing subtleties I should be aware of?

 Thanks.

**Comment by andreamad8** [comment]
- So I assume the 0 means that they are a KB entry correct? 
yes 
- Then the 1, 2,3 are for the actual dialogue turns.
yes
- Also for the KB entries how do you decide how many items to have? Some seem to be the standard KB triplet ravenswood_shopping_center distance 6_miles whereas other seem to be longer like 4_miles heavy_traffic coffee_or_tea_place poi philz?
yes, Poi and Weather need different info in the tuple. For sure there is a better way to do this, but the main points here is to have all the tokens you need in your response in the same line separated by space. So the model can copy such independent token.
- Also are there are any other preprocessing subtleties I should be aware of?
In MWOZ there are many actually. I converted MWOZ to an end-to-end dataset already. In my view, It is very challenging for many reasons, If you are interested maybe we could have a chat, in case contact me by email (amadotto@connect.ust.hk). I am very happy to help. :)
