### ISSUE TITLE
About import

### ISSUE THREAD

**Issue by qingyue2014** [HLTCHKUST/Mem2Seq#24]
Can you tell me the version of python?
I'm trying to use python 3.5 to run this code. I've install the latest version of pandas in my python env. But it always report error that "ImportError: No module named 'pandas.compat'".

**Comment by andreamad8** [comment]
From what I remember we used python 3, I don't remember the exact version. 

Have you tried:

pip uninstall pandas
pip install pandas

**Comment by qingyue2014** [comment]
> 
> 
> From what I remember we used python 3, I don't remember the exact version.
> 
> Have you tried:
> 
> pip uninstall pandas
> pip install pandas

I googled my problem and someone said that  "Matpoltlib 3.0.2 is required". I found that this version package must rely on python 3.6 and above. 
So I try python3.6 and install matpoltlib 3.0.2 and this equipment works! 
Thanks!

**Comment by andreamad8** [comment]
Cool. 

Andrea
