### ISSUE TITLE
RuntimeError: cuDNN version mismatch: PyTorch was compiled against 7003 but linked against 7300

### ISSUE THREAD

**Issue by shaficse** [HLTCHKUST/Mem2Seq#4]
I have faced this problem . In your readme also does not contain any clarification about the cuda and cudnn version . Could you please clarify to solve this problem . Thank you in advance .

**Comment by andreamad8** [comment]
Which version of pytorch are your running? and which version of cuda?

In this repo we used pytorch 0.3 and cuda 8. 

Let me know.

Andrea

**Comment by shaficse** [comment]
Thank you sir . I Had solved it . My cuda was 9 , I had shifted to cuda 8 now . Its working  . Right now I am going through your implementation .. If I face new problem then I will contact with you again. Thank you .
