### ISSUE TITLE
tokenisation script

### ISSUE THREAD

**Issue by arpitg1991** [HLTCHKUST/Mem2Seq#5]
Hi,
Could you share the script you use to tokenize kvret dataset to txt files. There are several non trivial transformations which are hard to replicate. 

Thanks

**Comment by jasonwu0731** [comment]
https://github.com/HLTCHKUST/Mem2Seq/blob/master/data/KVR/read_data.py

**Comment by arpitg1991** [comment]
There is probably some lower casing issue here. I get errors like these:
#navigate#
0 2_miles road_block_nearby parking_garage poi dish_parking
Traceback (most recent call last):
  File "read_data.py", line 119, in <module>
    print("0 {} {} ".format(poi, slot)+di[el[slot]])
KeyError: 'dish parking'
