### ISSUE TITLE
https://github.com/HLTCHKUST/Mem2Seq/blob/master/data/KVR/read_data.py

### ISSUE THREAD

**Issue by arpitg1991** [HLTCHKUST/Mem2Seq#6]
_Originally posted by @jasonwu0731 in https://github.com/HLTCHKUST/Mem2Seq/issues/5#issuecomment-439222335_

Thanks for quick reply. There is some lower casing issue. I get errors like these:
 
#navigate#
0 2_miles road_block_nearby parking_garage poi dish_parking
Traceback (most recent call last):
  File "read_data.py", line 119, in <module>
    print("0 {} {} ".format(poi, slot)+di[el[slot]])
KeyError: 'dish parking'

**Comment by arpitg1991** [comment]
Actually, I think the script is not reading POI from kvret_entities.json

**Comment by jasonwu0731** [comment]
maybe I upload the wrong version. I just uploaded one, please check.

**Comment by arpitg1991** [comment]
This works, thanks.
