### ISSUE TITLE
a probe about main_test.py

### ISSUE THREAD

**Issue by willionZS** [HLTCHKUST/Mem2Seq#7]
after training data,and have saved the model,but when I use the model to test,there is a IndexError:list index out of range,So, what's the wrong ?
I just do this: python3 main_test.py -dec=Mem2Seq -path=save\mem2seq-BABI -bsz=8 -ds=babi
thank you very much!!

**Comment by jasonwu0731** [comment]
sorry for the inconvenient. The origin code uploaded does not pass the correct KB path. Please check the following line for the update or pull the code again. Thanks.
https://github.com/HLTCHKUST/Mem2Seq/blob/master/models/Mem2Seq.py#L272
